apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: cartservice
  spec:
    selector:
      matchLabels:
        app: cartservice
    template:
      metadata:
        labels:
          app: cartservice
      spec:
        containers:
        - env:
          - name: REDIS_ADDR
            value: redis-cart:6379
          - name: PORT
            value: "7070"
          - name: LISTEN_ADDR
            value: 0.0.0.0
          image: gcr.io/opencensus-microservices-demo/cartservice
          livenessProbe:
            exec:
              command:
              - /cartservice_probe
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: server
          ports:
          - containerPort: 7070
          readinessProbe:
            exec:
              command:
              - /cartservice_probe
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 300m
              memory: 128Mi
            requests:
              cpu: 200m
              memory: 64Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 5
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: cartservice
  spec:
    ports:
    - name: grpc
      port: 7070
      protocol: TCP
      targetPort: 7070
    selector:
      app: cartservice
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata: {}
